version: '3'
services:
  dockerhub-test:
    build:
      context: .
      dockerfile: ./Dockerfile.develop
    image: dockerhub-test
    container_name: dockerhub-test   
    restart: always
    volumes: 
      - .:/app/
      - /app/node_modules
    ports:
      - "3040:3040"
    command: sh -c 'npm run dev'
